(part "2601-1102"
    (packageRef "26011102")
    (interface
        (port "1" (symbPinId 1) (portName "1.1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "1.2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "2.1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "2.2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Wago")
    (property "Manufacturer_Part_Number" "2601-1102")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "2601-1102")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/2601-1102/wago-kontakttechnik-gmbh.html?utm_currency=USD&region=asia")
    (property "Description" "PCB terminal block; lever; 1.5 mm; Pin spacing 3.5 mm; 2-pole; Push-in CAGE CLAMP; 1,50 mm; gray")
    (property "Datasheet_Link" "https://www.wago.com/2601-1102")
    (property "symbolName1" "2601-1102")
)
